<?php

namespace Database\Seeders;

use App\Models\BuffItem;
use App\Models\DebuffItem;
use App\Models\HealItem;
use App\Models\Item;
use App\Models\Monster;
use App\Models\Weapon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;

class ProdMonsterSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    Artisan::call('rpg:clear');
    DB::transaction(function () {
      // itemsテーブルにinsertした後に、対応するheal_items, buff_teble, debuff_tableを追加する
      $items = [
        [
          "id" => 1,
          "name" => "薬草",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/tScxu7ni1MSflYYtuzjhVInNAAa5xI1kn1Q2Nhny.png",
          "index_number" => "000",
          "effect_type" => "heal",
          "heal" => [
            "amount" => 35
          ],
        ],
        [
          "id" => 5,
          "name" => "スラッシュアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/9w0VkKHoJoMDFyMsvmKPUFGQ6VuCwEZ9yRD26U2G.png",
          "index_number" => "010",
          "effect_type" => "buff",
          "buff" => [
            "target" => "slash",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 6,
          "name" => "ブロウアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/yMx2aBcf3pH7Rau3ov6iGHCSdFfeidroGu8hXzRh.png",
          "index_number" => "020",
          "effect_type" => "buff",
          "buff" => [
            "target" => "blow",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 7,
          "name" => "シュートアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/VccDyJY07F97diGqTrnNhNl1vHwtICR5lOzGtWky.png",
          "index_number" => "030",
          "effect_type" => "buff",
          "buff" => [
            "target" => "shoot",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 8,
          "name" => "ニュートラルアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/KrcQuGTtVSXU8orDMq34jwLdIsmMwx66Zk1DALxM.png",
          "index_number" => "040",
          "effect_type" => "buff",
          "buff" => [
            "target" => "neutral",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 9,
          "name" => "フレイムアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/7oGyk3THvXOSBlW9z3fs8IMTLQeaMLslmx2dbkSg.png",
          "index_number" => "050",
          "effect_type" => "buff",
          "buff" => [
            "target" => "flame",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 10,
          "name" => "ウォーターアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/jIGRcDIvk5yas1CADmAbeMdv151RQlrjFWsNjrhh.png",
          "index_number" => "060",
          "effect_type" => "buff",
          "buff" => [
            "target" => "water",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 11,
          "name" => "ウッドアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/YRBGLNRIjVBAMAG3EHCIyBHsaTrbm0lWMNyU2u1n.png",
          "index_number" => "070",
          "effect_type" => "buff",
          "buff" => [
            "target" => "wood",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 12,
          "name" => "シャインアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/VcQrEmZDhze9gC6Lv6wpWoO2ZCHjMgoZF5FTBVyQ.png",
          "index_number" => "080",
          "effect_type" => "buff",
          "buff" => [
            "target" => "shine",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 13,
          "name" => "ダークアッパー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/m6Y0u7efE0zp8pDJbx3IzrgBYDy96LTzIyweZMcI.png",
          "index_number" => "090",
          "effect_type" => "buff",
          "buff" => [
            "target" => "dark",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 14,
          "name" => "スラッシュアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/rt1O4b4YtJ6kCvL1vEDIaHGu5e2ZLTbpEBGvRIpf.png",
          "index_number" => "011",
          "effect_type" => "buff",
          "buff" => [
            "target" => "slash",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 15,
          "name" => "ブロウアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/3mmrxG8b4kWQBJ5gfyMX6HSRO3I05igCutzp8hjy.png",
          "index_number" => "021",
          "effect_type" => "buff",
          "buff" => [
            "target" => "blow",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 16,
          "name" => "シュートアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/ON2Rs3Dn8tTq1hb0q4uxQHaGPpDVhcJ779XEwASY.png",
          "index_number" => "031",
          "effect_type" => "buff",
          "buff" => [
            "target" => "shoot",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 17,
          "name" => "ニュートラルアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/MdtvGwHqnbIJ5CGQO3gD9g7kbSG60PyLkM3DM47q.png",
          "index_number" => "041",
          "effect_type" => "buff",
          "buff" => [
            "target" => "neutral",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 18,
          "name" => "フレイムアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/lrPeLGOMg5FuLGnj8WxkU57XYBnWGBv2IPs5Vp7D.png",
          "index_number" => "051",
          "effect_type" => "buff",
          "buff" => [
            "target" => "flame",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 19,
          "name" => "ウォーターアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/FgqzUsbTxC2esh9bTLyMpNa1bXq72H3LG827OgOL.png",
          "index_number" => "061",
          "effect_type" => "buff",
          "buff" => [
            "target" => "water",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 20,
          "name" => "ウッドアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/UKABzAMVLkfoO2uGLdxd3eZ1bpOwfDVKvKHLwlKR.png",
          "index_number" => "071",
          "effect_type" => "buff",
          "buff" => [
            "target" => "wood",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 21,
          "name" => "シャインアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/pHHIu8lOamBuV1UI6piwsLGCirGcSwur5oDRhzI2.png",
          "index_number" => "081",
          "effect_type" => "buff",
          "buff" => [
            "target" => "shine",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 22,
          "name" => "ダークアッパー＋",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/gvPGxGwgaRdKmoJxvVjllarOsdtyEZAuBTmki4T0.png",
          "index_number" => "091",
          "effect_type" => "buff",
          "buff" => [
            "target" => "dark",
            "rate" => 0.6
          ]
        ],
        [
          "id" => 23,
          "name" => "スラッシュダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/63w6Q9sky21e4e2uSFz67qCUChxvbYmxa83JfMWV.png",
          "index_number" => "100",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "slash",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 24,
          "name" => "ブロウダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/wlSI0KJK3PKReauUFpcb89okI2bnkzrPeNbxLekl.png",
          "index_number" => "110",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "blow",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 25,
          "name" => "シュートダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/mx8J3OSglP6T9ZiTVYpJx2xWFDbgEmnAOi6B0OV6.png",
          "index_number" => "120",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "shoot",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 26,
          "name" => "ニュートラルダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/4NHM4J3rfDKQhsPxh8LG5JJTdJ7QTlJ0qjHc7JAC.png",
          "index_number" => "130",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "neutral",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 27,
          "name" => "フレイムダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/n2p2Rhse4NF99eqlLHXHfIdNPlSpjW1Mo8rFax0K.png",
          "index_number" => "140",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "flame",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 28,
          "name" => "ウォーターダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/AqeCBHjGOBf056usvpHonQVBTnWGioTrSv4GXtTO.png",
          "index_number" => "150",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "water",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 29,
          "name" => "ウッドダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/7JeHeHTiurX1B0FXE7FHCDVWIJr5xc5GazLFhQv8.png",
          "index_number" => "160",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "wood",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 30,
          "name" => "シャインダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/ce5sz16BU1JKo0yvS82X7XIeg9XE1BcDQm6yG1Jp.png",
          "index_number" => "170",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "shine",
            "rate" => 0.3
          ]
        ],
        [
          "id" => 31,
          "name" => "ダークダウナー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/item_images/mg6LudiIIb8EYTAjXf9EtDjHTZV2Lm5fbTETfeKG.png",
          "index_number" => "180",
          "effect_type" => "debuff",
          "debuff" => [
            "target" => "dark",
            "rate" => 0.3
          ]
        ],
      ];
      foreach ($items as $itemData) {
        $item = Item::create([
          'id'           => $itemData['id'],
          'name'         => $itemData['name'],
          'image_url'    => $itemData['image_url'],
          'index_number' => $itemData['index_number'],
          'effect_type'  => $itemData['effect_type'],
        ]);

        switch ($itemData['effect_type']) {
          case 'heal':
            HealItem::create([
              'item_id' => $item->id,
              'amount'  => $itemData['heal']['amount'],
            ]);
            break;
          case 'buff':
            BuffItem::create([
              'item_id' => $item->id,
              'target'  => $itemData['buff']['target'],
              'rate'    => $itemData['buff']['rate'],
            ]);
            break;
          case 'debuff':
            DebuffItem::create([
              'item_id' => $item->id,
              'target'  => $itemData['debuff']['target'],
              'rate'    => $itemData['debuff']['rate'],
            ]);
            break;
        }
      }

      Weapon::insert([
        [
          "id" => 1,
          "name" => "ニルロンダガー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/8q0tggeNmh3hFWgr8Bw9fl1N6uABySi0Nbef9iEZ.png",
          "index_number" => "000",
          "physics_attack" => 21,
          "element_attack" => 10,
          "physics_type" => "slash",
          "element_type" => "neutral",
        ],
        [
          "id" => 2,
          "name" => "ブレイズロンダガー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/DFErzhy1gVdh73vli06MTaG9rV77ADAUXhChwsVK.png",
          "index_number" => "001",
          "physics_attack" => 21,
          "element_attack" => 10,
          "physics_type" => "slash",
          "element_type" => "flame",
        ],
        [
          "id" => 3,
          "name" => "アクアロンダガー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/6kt3H6MVJM6IHKaIepkDBGaMuxmEpLcGHv2BZ826.png",
          "index_number" => "002",
          "physics_attack" => 21,
          "element_attack" => 10,
          "physics_type" => "slash",
          "element_type" => "water",
        ],
        [
          "id" => 4,
          "name" => "リーフロンダガー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/tV1ZeezujE3QcHprBDVEC89caeDfk5U6BSOdS7Ge.png",
          "index_number" => "003",
          "physics_attack" => 21,
          "element_attack" => 10,
          "physics_type" => "slash",
          "element_type" => "wood",
        ],
        [
          "id" => 5,
          "name" => "グロウロンダガー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/CgQ7OUjJ1CPYqXQ3tBZ7TEZsN7Fsc1rEdc6KPwuF.png",
          "index_number" => "004",
          "physics_attack" => 21,
          "element_attack" => 10,
          "physics_type" => "slash",
          "element_type" => "shine",
        ],
        [
          "id" => 6,
          "name" => "ダークロウダガー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/FMcIa3j3JeOHFGyT7Jo37RRW4aVRKy1metWZbeVh.png",
          "index_number" => "005",
          "physics_attack" => 21,
          "element_attack" => 10,
          "physics_type" => "slash",
          "element_type" => "dark",
        ],
        [
          "id" => 7,
          "name" => "ニルマグハンマー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/PhudMUKJKwifU9TijhHm9gtGsaD61uMREc9kKVDZ.png",
          "index_number" => "030",
          "physics_attack" => 16,
          "element_attack" => 7,
          "physics_type" => "blow",
          "element_type" => "neutral",
        ],
        [
          "id" => 8,
          "name" => "ブレイズマグハンマー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/owBv2Gx9L2XT9DFeV4aMuFAPz5FjnL49D1eeZ94V.png",
          "index_number" => "031",
          "physics_attack" => 16,
          "element_attack" => 7,
          "physics_type" => "blow",
          "element_type" => "flame",
        ],
        [
          "id" => 9,
          "name" => "マリンマグハンマー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/4czqYnprhd9yJxiIYg1vpt9GJYve7XhaqGOXVdtE.png",
          "index_number" => "032",
          "physics_attack" => 16,
          "element_attack" => 7,
          "physics_type" => "blow",
          "element_type" => "water",
        ],
        [
          "id" => 10,
          "name" => "リーフマグハンマー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/INhw2ISLnhdy8lvZnRTBdhSzPPriS55F2NANTDLm.png",
          "index_number" => "033",
          "physics_attack" => 16,
          "element_attack" => 7,
          "physics_type" => "blow",
          "element_type" => "wood",
        ],
        [
          "id" => 11,
          "name" => "グロウマグハンマー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/SaXK1flnQs17J5q5UyFnjcMSEu5wzPjWCbP9i41b.png",
          "index_number" => "034",
          "physics_attack" => 16,
          "element_attack" => 7,
          "physics_type" => "blow",
          "element_type" => "shine",
        ],
        [
          "id" => 12,
          "name" => "ダークマグハンマー",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/3fgTxn1HnnlIxG7RHen4E4lhkytS1lvWjvD99kQV.png",
          "index_number" => "035",
          "physics_attack" => 16,
          "element_attack" => 7,
          "physics_type" => "blow",
          "element_type" => "dark",
        ],
        [
          "id" => 13,
          "name" => "ニルスカルボウ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/vBsmtbVJUqVlMfF8adIRhItHePUA5ntNExTLoZHo.png",
          "index_number" => "060",
          "physics_attack" => 26,
          "element_attack" => 9,
          "physics_type" => "shoot",
          "element_type" => "neutral",
        ],
        [
          "id" => 14,
          "name" => "ブレイズスカルボウ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/5DEX860wBTk6d79DsZYJYkfrwf6qT1sJe9cYaVVH.png",
          "index_number" => "061",
          "physics_attack" => 26,
          "element_attack" => 9,
          "physics_type" => "shoot",
          "element_type" => "flame",
        ],
        [
          "id" => 15,
          "name" => "アクアスカルボウ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/gxj9Yk2If9r7Hq6YkkoP4IKtTLCQhZS8SCnjQsvo.png",
          "index_number" => "062",
          "physics_attack" => 26,
          "element_attack" => 9,
          "physics_type" => "shoot",
          "element_type" => "water",
        ],
        [
          "id" => 16,
          "name" => "リーフスカルボウ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/8VMwbIw4xmX3YZJHeiYgRvEcEVoqTdtueRh43Wcn.png",
          "index_number" => "063",
          "physics_attack" => 26,
          "element_attack" => 9,
          "physics_type" => "shoot",
          "element_type" => "wood",
        ],
        [
          "id" => 17,
          "name" => "グロウスカルボウ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/h24bPjEjxchJmFi1qCAK2X9rGXrGy0XacBe1D7sh.png",
          "index_number" => "064",
          "physics_attack" => 26,
          "element_attack" => 9,
          "physics_type" => "shoot",
          "element_type" => "shine",
        ],
        [
          "id" => 18,
          "name" => "ダークスカルボウ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/weapon_images/w8dA31Iqc1BvNqObgYyAYX67gQZ7dXBYYk3VyF7f.png",
          "index_number" => "065",
          "physics_attack" => 26,
          "element_attack" => 9,
          "physics_type" => "shoot",
          "element_type" => "dark",
        ],
      ]);

      Monster::insert([
        [
          "id" => "6ecf6fbd-5309-42cc-a8d6-b90b9a03be24",
          "name" => "ニルスライム",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/SCLq6q85F2PEC3qBAvOiVaP7UogUNiw4taT7cVNE.png",
          "index_number" => "000",
          "attack" => 15,
          "hit_point" => 13,
          "experience_point" => 30,
          "slash" => -1.0,
          "blow" => -1.0,
          "shoot" => -1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "3d3adf61-aea1-4b49-9cf0-4944e7993f21",
          "name" => "ブレイズスライム",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/u7cZqONnZYe3lNZbImCTARYv2sMngAtrKbYvRJMF.png",
          "index_number" => "001",
          "attack" => 15,
          "hit_point" => 13,
          "experience_point" => 30,
          "slash" => -1.0,
          "blow" => -1.0,
          "shoot" => -1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => -1.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "7244a2dc-8e9f-4b84-95e8-aac07cd1ee1e",
          "name" => "アクアスライム",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/l88jUP6Ap5NLdWnOk4HtmpeDzbaBMB2mFXkqsIX6.png",
          "index_number" => "002",
          "attack" => 15,
          "hit_point" => 13,
          "experience_point" => 30,
          "slash" => -1.0,
          "blow" => -1.0,
          "shoot" => -1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => -1.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "249da176-3f8f-44d1-ace7-4131e1f0ce16",
          "name" => "リーフスライム",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/kTzv9zyTPkQ5fKPvzzBIdJpXlp7EGegzqT6WbUtD.png",
          "index_number" => "003",
          "attack" => 15,
          "hit_point" => 13,
          "experience_point" => 30,
          "slash" => -1.0,
          "blow" => -1.0,
          "shoot" => -1.0,
          "neutral" => 0.0,
          "flame" => -1.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "2342b34a-3404-437b-b08e-9628c82a5f9a",
          "name" => "グロウスライム",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/Ydze0M46z8lcw64Aco605d8ESCfNm86Jr502YG9W.png",
          "index_number" => "004",
          "attack" => 15,
          "hit_point" => 13,
          "experience_point" => 30,
          "slash" => -1.0,
          "blow" => -1.0,
          "shoot" => -1.0,
          "neutral" => 0.0,
          "flame" => -1.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "5e1a624f-1fbd-41dd-aeb1-7e5c8dbacd28",
          "name" => "ダークスライム",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/H6w76Ll7PAVWo545SS5s8qcMB0vTCT2hHK7xgPmv.png",
          "index_number" => "005",
          "attack" => 15,
          "hit_point" => 13,
          "experience_point" => 30,
          "slash" => -1.0,
          "blow" => -1.0,
          "shoot" => -1.0,
          "neutral" => 0.0,
          "flame" => -1.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "e7460063-b8b2-4a12-a8a7-a0a488a66b4e",
          "name" => "ニルデビルン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/LxRxmHVEBSx9t4SsvMe5d6HBqe2Ts1ITWM62oj3h.png",
          "index_number" => "010",
          "attack" => 8,
          "hit_point" => 20,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => -1.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "ccfcd7b1-4313-47ac-8fea-064096d7831b",
          "name" => "ブレイズデビルン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/iV5sOJlt6xR4QetBbuRjs1g2kq8FtvQxAS49j6Ep.png",
          "index_number" => "011",
          "attack" => 8,
          "hit_point" => 20,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.5,
          "water" => -1.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "c2493603-b5e4-4d97-b97e-74df1ac8309f",
          "name" => "アクアデビルン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/TXIAOpXs5uV364cjwVsVWOQwxt6MMfY59sFglQaE.png",
          "index_number" => "012",
          "attack" => 8,
          "hit_point" => 20,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.5,
          "wood" => -1.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "22b43074-3b01-4238-9c77-88b9d73117ce",
          "name" => "リーフデビルン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/5Hfgs9gFc9bgavUixOx0DRJ7iWS4RLQGsaZtYu5E.png",
          "index_number" => "013",
          "attack" => 8,
          "hit_point" => 20,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => -1.0,
          "water" => 0.0,
          "wood" => 0.5,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 1,
          "weapon_id" => null,
        ],
        [
          "id" => "9a3fe765-0b33-486d-9222-02374c42007d",
          "name" => "ニルマグ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/4T1ln5q2dCWgkq9vmrb1AmKbfsgFA1nTLdanhmXA.png",
          "index_number" => "020",
          "attack" => 9,
          "hit_point" => 21,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => -0.5,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 7,
        ],
        [
          "id" => "f70030be-d949-48e5-a90d-8cfa7b988b04",
          "name" => "ブレイズマグ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/PFijM2Bob3920fytEid4WCRNDdItTnIQUckRLuLg.png",
          "index_number" => "021",
          "attack" => 9,
          "hit_point" => 21,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.5,
          "water" => -0.5,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 8,
        ],
        [
          "id" => "ed6c1266-cd6e-4904-9004-a51cc5f23e39",
          "name" => "アクアマグ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/bXiBVCMrUKFH9XH67h0Xm2W7BEwlL51xyZBc7eDm.png",
          "index_number" => "022",
          "attack" => 9,
          "hit_point" => 21,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.5,
          "wood" => -0.5,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 9,
        ],
        [
          "id" => "c3569843-8228-41f7-803c-d7f4f673a333",
          "name" => "リーフマグ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/SYNhxDGdq5gRPi6vLT5qcJ4hK2urfv0S29BHEMHC.png",
          "index_number" => "023",
          "attack" => 9,
          "hit_point" => 21,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => -0.5,
          "water" => 0.0,
          "wood" => 0.5,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 10,
        ],
        [
          "id" => "6a4898e5-33a3-432d-8775-327f45f95487",
          "name" => "グロウマグ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/XyQ8vVsDeVVrG5IaVzH9apq8CjjcHdtpQCRLaYiD.png",
          "index_number" => "024",
          "attack" => 9,
          "hit_point" => 21,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.5,
          "dark" => -0.5,
          "item_id" => null,
          "weapon_id" => 11,
        ],
        [
          "id" => "058993c2-16fb-4b2f-bdb0-3f84178d79fc",
          "name" => "ダークマグ",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/LSrkp4CBeemuSRhfVljWEga3xy612aZRXbn9ntWj.png",
          "index_number" => "025",
          "attack" => 9,
          "hit_point" => 21,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => -0.5,
          "dark" => 0.5,
          "item_id" => null,
          "weapon_id" => 12,
        ],
        [
          "id" => "295b36c9-6e42-47aa-94fe-0f54649ac8c5",
          "name" => "ニルロン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/8Ye1Dn6JyS9FVbPjVme6KSBiLNDkZSMCpSVE3QiZ.png",
          "index_number" => "030",
          "attack" => 26,
          "hit_point" => 9,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => -0.2,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 1,
        ],
        [
          "id" => "add88610-525e-48d2-880c-3e698625752b",
          "name" => "ブレイズロン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/SjRCQvtIyQmMNKwqfSOECUSvv8368ngJo6ioa1qY.png",
          "index_number" => "031",
          "attack" => 26,
          "hit_point" => 9,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.5,
          "water" => -0.2,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 2,
        ],
        [
          "id" => "b61a284c-0760-4869-8527-2457e9d5f414",
          "name" => "アクアロン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/uXVJlBdPTPa1ZO1nJnLdZe3X93ZbdjofBbgrPN4t.png",
          "index_number" => "032",
          "attack" => 26,
          "hit_point" => 9,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.5,
          "wood" => -0.2,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 3,
        ],
        [
          "id" => "37228913-a627-4c32-a307-7b869f3e42a5",
          "name" => "リーフロン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/BQCBsSAbKxIBiByDt6kMH6DtkNeS4OSuxMhybGwe.png",
          "index_number" => "033",
          "attack" => 26,
          "hit_point" => 9,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => -0.2,
          "water" => 0.0,
          "wood" => 0.5,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 4,
        ],
        [
          "id" => "7109b213-cf5e-4b48-8da5-e38633d55ac4",
          "name" => "グロウロン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/6HUExVxnAD6toNnYaWOLQqA91MaSwoDS1PnPgfIw.png",
          "index_number" => "034",
          "attack" => 26,
          "hit_point" => 9,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.5,
          "dark" => -0.2,
          "item_id" => null,
          "weapon_id" => 5,
        ],
        [
          "id" => "a6e0eebe-2289-4324-93c9-dd01b9151831",
          "name" => "ダークロン",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/N5Q000ThsyHZYLlBcXpKePfmf8uxfAqJh4xkjBR5.png",
          "index_number" => "035",
          "attack" => 26,
          "hit_point" => 9,
          "experience_point" => 30,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => -0.2,
          "dark" => 0.5,
          "item_id" => null,
          "weapon_id" => 6,
        ],
        [
          "id" => "759adcd2-4894-4fd2-a511-ad88e1508af4",
          "name" => "ニルゴルド",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/98piOlHMGBPyG3rtwsh7aYTzuy4qlGputhw0op8D.png",
          "index_number" => "040",
          "attack" => 4,
          "hit_point" => 50,
          "experience_point" => 34,
          "slash" => 1.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => -0.5,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 8,
          "weapon_id" => null,
        ],
        [
          "id" => "7845f011-502c-46f9-aba1-5ab1e4562e97",
          "name" => "ブレイズゴルド",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/pqku43mdu9q2zugJmMdSor3nhjHw3LEVfRkpCEau.png",
          "index_number" => "041",
          "attack" => 4,
          "hit_point" => 50,
          "experience_point" => 34,
          "slash" => 1.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 1.2,
          "water" => -0.5,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 9,
          "weapon_id" => null,
        ],
        [
          "id" => "43e5780c-bc5d-4aa9-b711-f1f70cf27187",
          "name" => "アクアゴルド",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/sE2XVh7Hixlol6sbDAhW8PIt6SNDzwFeOlrUHQKL.png",
          "index_number" => "042",
          "attack" => 4,
          "hit_point" => 50,
          "experience_point" => 34,
          "slash" => 1.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 1.2,
          "wood" => -0.5,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 10,
          "weapon_id" => null,
        ],
        [
          "id" => "55eb031b-7ac0-4fe0-a8ab-4ce3735a2e73",
          "name" => "リーフゴルド",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/Ez7GMvNrJwFJQ1gvqOgO58ZYFzfItXM8NtneabUn.png",
          "index_number" => "043",
          "attack" => 4,
          "hit_point" => 50,
          "experience_point" => 34,
          "slash" => 1.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => -0.5,
          "water" => 0.0,
          "wood" => 1.2,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 11,
          "weapon_id" => null,
        ],
        [
          "id" => "7e690b92-b864-4c06-a490-2dab0ae2efc9",
          "name" => "グロウゴルド",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/OVgUPMcGi5GijZWFF2yjiCXyXNaDi9YGOZbexjgX.png",
          "index_number" => "044",
          "attack" => 4,
          "hit_point" => 50,
          "experience_point" => 34,
          "slash" => 1.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 1.2,
          "dark" => -0.5,
          "item_id" => 12,
          "weapon_id" => null,
        ],
        [
          "id" => "74a8edef-6c94-4c1b-a6a2-483d7129cbf9",
          "name" => "ダークゴルド",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/NgAWTw8TFO57BIx6TUBma8nvoWibbqG6vn5Q0kvq.png",
          "index_number" => "045",
          "attack" => 4,
          "hit_point" => 50,
          "experience_point" => 34,
          "slash" => 1.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => -0.5,
          "dark" => 1.2,
          "item_id" => 13,
          "weapon_id" => null,
        ],
        [
          "id" => "ef33b3c0-53fc-4aa0-9041-33d14ce80d1a",
          "name" => "ニルウィザード",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/eC8Yj7H5kUuS8flJhsUGuZzMBVFOAeINP2paeehC.png",
          "index_number" => "050",
          "attack" => 42,
          "hit_point" => 48,
          "experience_point" => 38,
          "slash" => 0.5,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => -0.8,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 8,
          "weapon_id" => null
        ],
        [
          "id" => "4e759a62-5268-41ac-8ef0-230c1a3f87d7",
          "name" => "ブレイズウィザード",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/3xiG7WMSxiKrNNj6YGm723GUkn42w2PZWIIJpquB.png",
          "index_number" => "051",
          "attack" => 42,
          "hit_point" => 48,
          "experience_point" => 38,
          "slash" => 0.5,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 1.2,
          "water" => -0.8,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 9,
          "weapon_id" => null
        ],
        [
          "id" => "b5b40c9a-43c6-4a13-8586-2b558feef439",
          "name" => "アクアウィザード",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/LH4xZk8PHZEkRgswnORcvwoBmZpn3Vwocfj8xi5U.png",
          "index_number" => "052",
          "attack" => 42,
          "hit_point" => 48,
          "experience_point" => 38,
          "slash" => 0.5,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 1.2,
          "wood" => -0.8,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 10,
          "weapon_id" => null
        ],
        [
          "id" => "b0f91ee4-4282-4f67-a6ca-9a9973326909",
          "name" => "リーフウィザード",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/2sG32fjWGoyuFZ7YM5WOz51bRo4NYpEdyOF6x0zN.png",
          "index_number" => "053",
          "attack" => 42,
          "hit_point" => 48,
          "experience_point" => 38,
          "slash" => 0.5,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => -0.8,
          "water" => 0.0,
          "wood" => 1.2,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => 11,
          "weapon_id" => null
        ],
        [
          "id" => "64394bc4-c9c8-41bb-98f0-b2cf58e10439",
          "name" => "グロウウィザード",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/jf54fvzECaITiUJLyXY6ZqwrifiLLAXOBx1Z9B9F.png",
          "index_number" => "054",
          "attack" => 42,
          "hit_point" => 48,
          "experience_point" => 38,
          "slash" => 0.5,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 1.2,
          "dark" => -0.8,
          "item_id" => 12,
          "weapon_id" => null
        ],
        [
          "id" => "67e35bc3-7551-43c8-ac08-dc84c2d61e31",
          "name" => "ダークウィザード",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/3iFDAJ4mKtoIIcxOCSaVubmKAPMqzSoAWuK5nOzn.png",
          "index_number" => "055",
          "attack" => 42,
          "hit_point" => 48,
          "experience_point" => 38,
          "slash" => 0.5,
          "blow" => 0.0,
          "shoot" => 0.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => -0.8,
          "dark" => 1.2,
          "item_id" => 13,
          "weapon_id" => null
        ],
        [
          "id" => "b64f7746-6180-43af-b216-2c4a366ac140",
          "name" => "ニルスカル",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/2evhp330Mmi9LaYtXadCXCEvRuVsxsokVTecEwQs.png",
          "index_number" => "060",
          "attack" => 48,
          "hit_point" => 75,
          "experience_point" => 40,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => -0.2,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 13,
        ],
        [
          "id" => "090ca6dd-c57b-4a20-8de0-66011eba5cbe",
          "name" => "ブレイズスカル",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/0rz3vH57uC05ps4NmCfWzwrNiKR6DMkbiUbEvdfg.png",
          "index_number" => "061",
          "attack" => 48,
          "hit_point" => 75,
          "experience_point" => 40,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 1.0,
          "water" => -0.2,
          "wood" => 0.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 14,
        ],
        [
          "id" => "210b10fc-97e9-4fee-aa7a-cc218e2f09bd",
          "name" => "アクアスカル",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/lkukaxc1ccho7PlUdcO927pOdE7uhinVokp41Hej.png",
          "index_number" => "062",
          "attack" => 48,
          "hit_point" => 75,
          "experience_point" => 40,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 1.0,
          "wood" => -0.2,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 15,
        ],
        [
          "id" => "41211643-70eb-4eb7-8276-2b8c055af1af",
          "name" => "リーフスカル",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/JjAI1KPefZJ1ynOl6Hrb0EzMZnwNT4ZUPgE6sTe7.png",
          "index_number" => "063",
          "attack" => 48,
          "hit_point" => 75,
          "experience_point" => 40,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => -0.2,
          "water" => 0.0,
          "wood" => 1.0,
          "shine" => 0.0,
          "dark" => 0.0,
          "item_id" => null,
          "weapon_id" => 16,
        ],
        [
          "id" => "be923333-a4d0-427f-8d0b-03f29b84e704",
          "name" => "グロウスカル",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/K1Mb1TUxLCGmZY9a6PAiO78mO531Z6Wf1zOQFVZp.png",
          "index_number" => "064",
          "attack" => 48,
          "hit_point" => 75,
          "experience_point" => 40,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => 1.0,
          "dark" => -0.2,
          "item_id" => null,
          "weapon_id" => 17,
        ],
        [
          "id" => "6fac2960-44fc-4a34-8c1e-198f398f4ca3",
          "name" => "ダークスカル",
          "image_url" => "https://s3-bunkasairpg.s3.ap-northeast-1.amazonaws.com/monster_images/OluTxI9PrmHrpyIOnqlbF67liRG3NhamjLSLhKoU.png",
          "index_number" => "065",
          "attack" => 48,
          "hit_point" => 75,
          "experience_point" => 40,
          "slash" => 0.0,
          "blow" => 0.0,
          "shoot" => 1.0,
          "neutral" => 0.0,
          "flame" => 0.0,
          "water" => 0.0,
          "wood" => 0.0,
          "shine" => -0.2,
          "dark" => 1.0,
          "item_id" => null,
          "weapon_id" => 18,
        ],
      ]);
    });
  }
}
